# Generated by Django 3.2 on 2021-05-12 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('position', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(max_length=500, null=True)),
                ('experience', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('skills', models.CharField(max_length=30, null=True)),
                ('salary', models.CharField(max_length=30, null=True)),
                ('timee', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='allusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'female'), ('other', 'other')], max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.add_job')),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.studentuser')),
            ],
        ),
        migrations.AddField(
            model_name='add_job',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.catagory'),
        ),
        migrations.AddField(
            model_name='add_job',
            name='recruiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter'),
        ),
    ]
